// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Validators;
using Elements.Serialization.JSON;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace Grid2dExample
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v12.0.0.0)")]
    
    public  class Grid2dExampleInputs : S3Args
    
    {
        [Newtonsoft.Json.JsonConstructor]
        
        public Grid2dExampleInputs(IList<Polygon> @gridBoundaries, Transform @gridAlignmentTransform, IList<Vector3> @uSplitPoints, IList<Vector3> @vSplitPoints, string bucketName, string uploadsBucket, Dictionary<string, string> modelInputKeys, string gltfKey, string elementsKey, string ifcKey):
        base(bucketName, uploadsBucket, modelInputKeys, gltfKey, elementsKey, ifcKey)
        {
            var validator = Validator.Instance.GetFirstValidatorForType<Grid2dExampleInputs>();
            if(validator != null)
            {
                validator.PreConstruct(new object[]{ @gridBoundaries, @gridAlignmentTransform, @uSplitPoints, @vSplitPoints});
            }
        
            this.GridBoundaries = @gridBoundaries;
            this.GridAlignmentTransform = @gridAlignmentTransform;
            this.USplitPoints = @uSplitPoints;
            this.VSplitPoints = @vSplitPoints;
        
            if(validator != null)
            {
                validator.PostConstruct(this);
            }
        }
    
        [Newtonsoft.Json.JsonProperty("Grid Boundaries", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public IList<Polygon> GridBoundaries { get; set; }
    
        [Newtonsoft.Json.JsonProperty("Grid Alignment Transform", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Transform GridAlignmentTransform { get; set; }
    
        [Newtonsoft.Json.JsonProperty("U Split Points", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public IList<Vector3> USplitPoints { get; set; }
    
        [Newtonsoft.Json.JsonProperty("V Split Points", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public IList<Vector3> VSplitPoints { get; set; }
    
    
    }
}